# Site settings
title: Permaprendices
description: Un laboratorio móvil de lo posible. Plantamos dudas, cosechamos fiestas.
url: "https://permaprendices.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:title/"
logo: 'assets/img/logo.png'
lang: es

locale: es_ES
timezone: Europe/Madrid # Necesita la gem 'tzinfo-data'

favicon: 'assets/favicon.ico'

twitter: permaprendices

feed:
  path: feed.xml
  excerpt_only: true

# Build settings
markdown: kramdown

# SASS
sass:
  style: :compressed

# Defaults
defaults:
  - scope:
      path: "*"
    values:
      layout: default

# Exclude
exclude:
  - vendor
  - assets/js/bootstrap.bundle.min.js
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
